.PHONY: clean all install uninstall test testclean
all:
	echo running..
	$(MAKE) -C network-stack-abstraction all
	$(MAKE) -C control-channel all
clean:
	echo running..
	$(MAKE) -C network-stack-abstraction clean
	$(MAKE) -C control-channel clean
install:
	echo running..
	$(MAKE) -C network-stack-abstraction install
	$(MAKE) -C control-channel install
