#include "DHCPv4_CLIENT_REQUEST.h"

int main()
{
	DHCPv4_CLIENT_REQUEST_01();
	DHCPv4_CLIENT_REQUEST_02();
	DHCPv4_CLIENT_REQUEST_06();
	DHCPv4_CLIENT_REQUEST_07();
	DHCPv4_CLIENT_REQUEST_08();
	DHCPv4_CLIENT_REQUEST_09();
	DHCPv4_CLIENT_REQUEST_10();
	DHCPv4_CLIENT_REQUEST_11();
	DHCPv4_CLIENT_REQUEST_12();
    	return 0;
}

