#include "DHCPv4_CLIENT_REACQUISITION.h"

int main()
{
	DHCPv4_CLIENT_REACQUISITION_01();
	DHCPv4_CLIENT_REACQUISITION_02();
	DHCPv4_CLIENT_REACQUISITION_03();
	DHCPv4_CLIENT_REACQUISITION_04();
	DHCPv4_CLIENT_REACQUISITION_05();
	DHCPv4_CLIENT_REACQUISITION_06();
	DHCPv4_CLIENT_REACQUISITION_07();
	DHCPv4_CLIENT_REACQUISITION_08();
    	return 0;
}


