#include "DHCPv4_CLIENT_INITIALIZATION_ALLOCATION.h"

int main()
{
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_01();
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_02();
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_03();
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_04();
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_05();
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_06();
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_08();
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_09();
	DHCPv4_CLIENT_INITIALIZATION_ALLOCATION_10();
    	return 0;
}


