#include "DHCPv4_CLIENT_ALLOCATING.h"

int main()
{
	DHCPv4_CLIENT_ALLOCATING_01();
	DHCPv4_CLIENT_ALLOCATING_03();
	DHCPv4_CLIENT_ALLOCATING_04();
	DHCPv4_CLIENT_ALLOCATING_05();
	DHCPv4_CLIENT_ALLOCATING_06();
	DHCPv4_CLIENT_ALLOCATING_07();
	DHCPv4_CLIENT_ALLOCATING_08();
	DHCPv4_CLIENT_ALLOCATING_09();
	DHCPv4_CLIENT_ALLOCATING_10();
    	return 0;
}


