all:
	echo running..
	$(MAKE) -C com-module all
	$(MAKE) -C com-module all
	$(MAKE) -C com-module all
clean:
	echo clean..
	$(MAKE) -C com-module clean
	$(MAKE) -C com-module clean
	$(MAKE) -C com-module clean
install:
	echo install..
	$(MAKE) -C com-module install
	$(MAKE) -C com-module install
	$(MAKE) -C com-module install
