all:
	echo running..
	$(MAKE) -C LinuxComModule all
	$(MAKE) -C LinuxComModule all
	$(MAKE) -C LinuxComModule all
clean:
	echo clean..
	$(MAKE) -C LinuxComModule clean
	$(MAKE) -C LinuxComModule clean
	$(MAKE) -C LinuxComModule clean
install:
	echo install..
	$(MAKE) -C LinuxComModule install
	$(MAKE) -C LinuxComModule install
	$(MAKE) -C LinuxComModule install
