all:
	echo building ..
	$(MAKE) -C TC8-ARP all
	$(MAKE) -C TC8-DHCP all
	$(MAKE) -C TC8-ICMP all
	$(MAKE) -C TC8-IPV4 all
	$(MAKE) -C TC8-SOMEIP all
	$(MAKE) -C TC8-TCP all
	$(MAKE) -C TC8-UDP all
clean:
	echo cleaning
	$(MAKE) -C TC8-ARP clean
	$(MAKE) -C TC8-DHCP clean
	$(MAKE) -C TC8-ICMP clean
	$(MAKE) -C TC8-IPV4 clean
	$(MAKE) -C TC8-SOMEIP clean
	$(MAKE) -C TC8-TCP clean
	$(MAKE) -C TC8-UDP clean
install:
	echo installing
	$(MAKE) -C TC8-ARP install
	$(MAKE) -C TC8-DHCP install
	$(MAKE) -C TC8-ICMP install
	$(MAKE) -C TC8-IPV4 install
	$(MAKE) -C TC8-SOMEIP install
	$(MAKE) -C TC8-TCP install
	$(MAKE) -C TC8-UDP install
